### ISSUE TITLE
Release documentation expected date

### ISSUE THREAD

**Issue by nguyenquivinhquang** [kingstonduy/OnlineLearning#1]
Thanks for your wonderful work,

Will we release the document so the end user can run this application?

**Comment by kingstonduy** [comment]
Dear @nguyenquivinhquang,

Thanks for paying attention to my works. The repo only contains ebooks that i p̵u̵b̵l̵i̵s̵h̵e̵d̵ collected. If you want to use any information in this repo please cite my name.

Feel free to use it.
